[package]
name = "fck_pure"
description = "The source code for the fck coding language"
version = "0.1.0"
authors = ["RosiePuddles <rosiegbartlett@gmail.om>"]
edition = "2018"
repository = "https://github.com/fck-language/fck"
homepage = "https://fck-language.github.io/fck"
readme = "README.md"
license = "GPL-3.0"

[badges]
maintenance = {status = "actively-developed"}

[dependencies]
clap = "2.33.3"
llvm-sys = "130"
lang = { path = "lang" }
